# PowerShell script to run load test with environment variables
# Usage: ./run-load-test.ps1 [test-type]

param(
    [string]$TestType = "load",
    [switch]$Help
)

if ($Help) {
    Write-Host "🚀 K6 Load Test Runner" -ForegroundColor Green
    Write-Host ""
    Write-Host "This script runs K6 load tests with environment variables from .env file."
    Write-Host ""
    Write-Host "Usage:"
    Write-Host "  ./run-load-test.ps1                    # Run default load test"
    Write-Host "  ./run-load-test.ps1 -TestType smoke    # Run smoke test"
    Write-Host "  ./run-load-test.ps1 -TestType load     # Run load test"
    Write-Host "  ./run-load-test.ps1 -TestType stress   # Run stress test"
    Write-Host "  ./run-load-test.ps1 -TestType spike    # Run spike test"
    Write-Host "  ./run-load-test.ps1 -Help              # Show this help"
    Write-Host ""
    Write-Host "Environment variables will be loaded from .env file automatically."
    Write-Host "See .env.example for required variables and SECURITY.md for practices."
    exit 0
}

# Validate test type
$validTypes = @("smoke", "load", "stress", "spike")
if ($TestType -notin $validTypes) {
    Write-Host "❌ Invalid test type: $TestType" -ForegroundColor Red
    Write-Host "Valid types: $($validTypes -join ', ')" -ForegroundColor Yellow
    exit 1
}

# Check if .env file exists, fallback to .env.local
$envFile = ".env"
if (!(Test-Path ".env")) {
    if (Test-Path ".env.local") {
        $envFile = ".env.local"
        Write-Host "📝 Using .env.local (development configuration)" -ForegroundColor Yellow
    } else {
        Write-Host "❌ Error: Neither .env nor .env.local file found" -ForegroundColor Red
        Write-Host "💡 Please copy .env.example to .env and configure your credentials" -ForegroundColor Yellow
        Write-Host "📖 See SECURITY.md for detailed setup instructions" -ForegroundColor Yellow
        exit 1
    }
} else {
    Write-Host "📝 Using .env file" -ForegroundColor Green
}

# Load environment variables from selected file
Write-Host "🔧 Loading environment variables from $envFile..." -ForegroundColor Blue

try {
    $envContent = Get-Content $envFile | Where-Object { $_ -match "^[^#].*=" }
    
    foreach ($line in $envContent) {
        if ($line -match "^([^=]+)=(.*)$") {
            $name = $Matches[1].Trim()
            $value = $Matches[2].Trim()
            
            # Remove quotes if present
            $value = $value -replace '^"(.*)"$', '$1'
            $value = $value -replace "^'(.*)'$", '$1'
            
            [Environment]::SetEnvironmentVariable($name, $value, "Process")
            Write-Host "  ✓ $name" -ForegroundColor DarkGreen
        }
    }
    
    # Set test configuration based on type
    $configFile = "$TestType-test.json"
    $testFile = "test-suite.js"
    
    # Override for smoke test to use simple version
    if ($TestType -eq "smoke") {
        $testFile = "simple-smoke-test.js"
        $configFile = "smoke-test.json"
    }
    
    Write-Host "🚀 Running $TestType test..." -ForegroundColor Green
    Write-Host "   Config: $configFile" -ForegroundColor Gray
    Write-Host "   Test: $testFile" -ForegroundColor Gray
    Write-Host ""
    
    # Create timestamp for results
    $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
    $resultsFile = "../../test-results/faas-$TestType-test-$timestamp.md"
    
    # Run K6 test and capture output
    Write-Host "📊 Test results will be saved to: $resultsFile" -ForegroundColor Blue
    
    # Create results header
    $nodeEnv = if ($env:NODE_ENV) { $env:NODE_ENV } else { 'development' }
    $header = @"
# FaaS $($TestType.ToUpper()) Test Results - $timestamp

## Test Configuration
- **Test Type**: $($TestType.ToUpper())
- **Config File**: $configFile
- **Test File**: $testFile
- **Start Time**: $(Get-Date)
- **Environment**: $nodeEnv

## Test Execution

```
"@
    
    $header | Out-File -FilePath $resultsFile -Encoding UTF8
    
    # Run K6 test
    $k6Output = & k6 run --config $configFile $testFile 2>&1
    $exitCode = $LASTEXITCODE
    
    # Append results to file
    $k6Output | Out-File -FilePath $resultsFile -Append -Encoding UTF8
    
    # Add footer
    $completionStatus = if($exitCode -eq 0) { "✅ Completed" } else { "❌ Failed" }
    $footer = @"
```

## Test Summary
- **Exit Code**: $exitCode
- **End Time**: $(Get-Date)
- **Duration**: $completionStatus

---
*Generated by run-load-test.ps1 - Framework: K6 Load Testing Suite for FaaS vs IaaS Migration*
"@
    
    $footer | Out-File -FilePath $resultsFile -Append -Encoding UTF8
    
    if ($exitCode -eq 0) {
        Write-Host ""
        Write-Host "✅ $($TestType.ToUpper()) test completed successfully!" -ForegroundColor Green
        Write-Host "📄 Results saved to: $resultsFile" -ForegroundColor Blue
    } else {
        Write-Host ""
        Write-Host "❌ $($TestType.ToUpper()) test failed with exit code: $exitCode" -ForegroundColor Red
        Write-Host "📄 Error details saved to: $resultsFile" -ForegroundColor Yellow
    }
    
    exit $exitCode
    
} catch {
    Write-Host "❌ Error running test: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}